# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_comment',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='profile_pic',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
