# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20191023_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_likes',
        ),
        migrations.AddField(
            model_name='image',
            name='image_likes',
            field=models.IntegerField(default=0),
        ),
    ]
