# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20191023_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_likes',
            new_name='like',
        ),
    ]
