# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20191018_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='AvatorPicture/'),
            preserve_default=False,
        ),
    ]
